### ISSUE TITLE
🛒 TimeDeal Registration Service Implementation

### ISSUE THREAD

**Issue by hyeonjeong-ko** [strong2team/shopingMall#8]
# 🛒 TimeDeal Registration Service Implementation

## 📋 Description
타임딜 예약 및 등록 API(`/api/time-deals`)를 구현하여 관리자가 타임딜 정보를 등록할 수 있도록함.
등록된 타임딜 정보는 DB와 S3에 저장되며, 예약된 시간에 활성화됨.
(시간 자동 활성화 부분은 아직 구현 전.) 

---

## ✨ Features
- **타임딜 등록 API** (`POST /api/time-deals`)
  - 관리자 권한 확인 후 타임딜 데이터 등록.
  - 상품 이미지를 URL에서 추출 후 S3에 업로드.
  - 타임딜 데이터와 이미지 URL을 데이터베이스에 저장.
- **타임딜 상태값(Enum) 추가**
  - 상태값: `SCHEDULED`, `ACTIVE`, `ENDED`, `DELETED`.
- **DB 스키마 수정**
  - `status` 컬럼을 `VARCHAR`로 변경.
  - 상태값에 따라 타임딜의 활성화 상태를 명확히 관리.

---

## 🔍 Why
- 타임딜 서비스 운영을 위해 관리자에게 상품 등록 기능 제공.
- S3를 활용하여 이미지 관리 효율성 및 데이터 안정성 확보.
- 타임딜 활성/비활성 상태를 명확히 구분하기 위해 `status` 값 추가.

---

## 🚀 Implementation Details
1. **API 개발**
   - `@PostMapping("/api/time-deals")`를 통해 타임딜 등록 API 구현.
   - 관리자 권한(`TIME_DEAL_MANAGER`) 확인 로직 포함.
2. **S3 연동**
   - 상품 이미지를 URL에서 추출 후 S3에 업로드.
   - 업로드된 이미지 URL을 `TimeDeal` 엔티티와 연결.
3. **DB 스키마 및 엔티티 변경**
   - `TimeDeal` 및 `Product` 엔티티 수정.
   - 상태값 관리 로직 추가 (`SCHEDULED` 등).
4. **프론트엔드와 연동**
   - 등록 성공/실패 메시지를 프론트에 반환.

---

## 🛠️ To-Do
- [x] 타임딜 등록 API 개발.
- [x] 이미지 URL에서 이미지 추출 및 S3 업로드 로직 구현.
- [x] 타임딜 상태값(Enum) 및 DB 컬럼 수정.
- [x] 프론트와 데이터 연동 테스트.
- [x] 관리자 권한 검증 로직 추가.

---

### **Request URL**
```http
POST /api/time-deals
